// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/testnew/pkg/models/shared"
	"net/http"
)

type SearchUsersv1Response struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Users *shared.Users
}

func (o *SearchUsersv1Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchUsersv1Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchUsersv1Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchUsersv1Response) GetUsers() *shared.Users {
	if o == nil {
		return nil
	}
	return o.Users
}
