// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Error - The `Status` type defines a logical error model
type Error struct {
	// A developer-facing error message.
	Message string `json:"message"`
	// The HTTP status code
	StatusCode int `json:"status_code"`
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Error) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}
