// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Filters - An array of filters are used to query requests.
type Filters struct {
	// A list of filters to apply to the query.
	Filters []Filter `json:"filters"`
	// The maximum number of results to return.
	Limit int64 `json:"limit"`
	// The offset to start the query from.
	Offset int64 `json:"offset"`
}

func (o *Filters) GetFilters() []Filter {
	if o == nil {
		return []Filter{}
	}
	return o.Filters
}

func (o *Filters) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *Filters) GetOffset() int64 {
	if o == nil {
		return 0
	}
	return o.Offset
}
