// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Filter - Filters are used to query requests.
type Filter struct {
	Field     string `json:"field"`
	Matchtype string `json:"matchtype"`
	Value     string `json:"value"`
}

func (o *Filter) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *Filter) GetMatchtype() string {
	if o == nil {
		return ""
	}
	return o.Matchtype
}

func (o *Filter) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
