// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserInput - The details of a typical user account
type UserInput struct {
	Country   string `json:"country"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Nickname  string `json:"nickname"`
	Password  string `json:"password"`
}

func (o *UserInput) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *UserInput) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *UserInput) GetFirstname() string {
	if o == nil {
		return ""
	}
	return o.Firstname
}

func (o *UserInput) GetLastname() string {
	if o == nil {
		return ""
	}
	return o.Lastname
}

func (o *UserInput) GetNickname() string {
	if o == nil {
		return ""
	}
	return o.Nickname
}

func (o *UserInput) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
