// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Users - An array of users.
type Users struct {
	// A list of users to return.
	Users []User `json:"users"`
}

func (o *Users) GetUsers() []User {
	if o == nil {
		return []User{}
	}
	return o.Users
}
